replicaCount: 1
image:
  repository: fenglc/pgadmin4
  tag:
  pullPolicy: IfNotPresent
service:
  name: pgadmin
  type: LoadBalancer
  externalPort: 5050
  internalPort: 5050
pgadmin:
  username: pgadmin4@pgadmin.org
  password: admin
persistence:
  enabled: true
  storageClass:
  accessMode: ReadWriteOnce
  size: 4Gi
resources: {}

